version: '3.8'

services:
  # MySQL Database Service
  mysql:
    image: mysql:8.0  # Use the latest stable MySQL image
    container_name: mysql_container
    restart: always
    ports:
      - "3306:3306"  # Expose MySQL on port 3306
    environment:
      MYSQL_ROOT_PASSWORD: password  # Replace with a strong password
      MYSQL_DATABASE: attendance_db      # Database name
      MYSQL_USER: user                   # Custom user
      MYSQL_PASSWORD: password       # Password for the custom user
    volumes:
      - mysql_data:/var/lib/mysql  # Persist MySQL data

# Define Volumes
volumes:
  mysql_data:

# Define Network
networks:
  app_network:
    driver: bridge

