# Server Configuration
server:
  port: 8080  # Change the port if needed

# Spring Datasource Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/attendance_db  # Replace with your database URL
    username: root                                  # Replace with your database username
    password: password                              # Replace with your database password
    driver-class-name: com.mysql.cj.jdbc.Driver     # MySQL driver

  jpa:
    hibernate:
      ddl-auto: update                              # Options: validate | update | create | create-drop
    show-sql: true                                  # Enable to view SQL queries in the logs
    properties:
      hibernate:
        format_sql: true                            # Format SQL queries for readability

# JWT Configuration
jwt:
  secret-key: your_secret_key                       # Use environment variable in production
  expiration-time: 36000000                         # Token validity in milliseconds (10 hours)

# Logging Configuration
logging:
  level:
    root: INFO
    org.springframework: DEBUG

