name: Basic Branch CI

on:
  push:
    branches:
      - '*'     # Trigger on any branch
      - '!main' # Exclude the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: branching

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Build Spring Boot JAR with Maven (Skipping Unit Tests)
        run: mvn -B package -DskipTests --file pom.xml