name: Debug Deploy Only

on:
  push:
    branches:
      - main  # Change this if needed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo (if needed)
      uses: actions/checkout@v3

    - name: Set up Railway CLI
      run: |
        curl -fsSL https://railway.app/install.sh | sh
        echo "$HOME/.railway/bin" >> $GITHUB_PATH

    - name: Create Dockerfile from Docker Hub image
      run: |
        echo "FROM ashishv01/facedec:latest" > Dockerfile

    - name: Deploy to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: railway up --service d8f2b40a-b9bf-49ae-84d4-2ad5fd3a379f
