name: Debug Deploy Only

on:
  push:
    branches:
      - main  # Change this if needed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: my-service
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}

    steps:
    - name: Create Dockerfile from Docker Hub image
      run: |
        echo "FROM ashishv01/facedec:latest" > Dockerfile

    - name: Is token available
      run: |
        if [ -n "$RAILWAY_TOKEN" ]; then 
          echo "Token is there";
        else 
          echo "Token not found";
          exit 1
        fi

    - name: Checking repo
      run: |
        ls -al
        cat Dockerfile

    - name: Deploy to Railway
      run: railway up --service d8f2b40a-b9bf-49ae-84d4-2ad5fd3a379f
